# Generated by Django 5.2.10 on 2026-02-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
        ('gestion_notes', '0001_initial'),
        ('structure_pedagogique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='gestion_academique.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='gestion_academique.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='structure_pedagogique.matiere', verbose_name='Matière'),
        ),
    ]
