# Generated by Django 5.2.10 on 2026-02-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academique', '0001_initial'),
        ('structure_pedagogique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Moyenne générale (/10)')),
                ('total_credits_obtenus', models.IntegerField(default=0, verbose_name='Crédits obtenus')),
                ('total_credits_requis', models.IntegerField(default=0, verbose_name='Crédits requis')),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('ajourne', 'Ajourné')], default='ajourne', max_length=20, verbose_name='Décision')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='gestion_academique.anneeacademique', verbose_name='Année académique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='gestion_academique.etudiant', verbose_name='Étudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='structure_pedagogique.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-genere_le'],
                'unique_together': {('etudiant', 'semestre', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Fichier PDF')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('telecharge_le', models.DateTimeField(blank=True, null=True, verbose_name='Téléchargé le')),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('resultat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin', to='bulletins.resultat', verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-genere_le'],
            },
        ),
    ]
