# Generated by Django 5.2.10 on 2026-02-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='date_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du passage'),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='passage_effectue',
            field=models.BooleanField(default=False, verbose_name="Passage d'année effectué"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('diplome', 'Diplômé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='EtudiantArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_diplome', models.CharField(choices=[('diplome', 'Diplômé'), ('non_diplome', 'Non diplômé')], max_length=20, verbose_name='Statut diplôme')),
                ('ue_manquantes', models.TextField(blank=True, help_text='Liste des codes UE non validées', verbose_name='UE manquantes (JSON)')),
                ('date_archivage', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('annee_sortie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sortants', to='gestion_academique.anneeacademique', verbose_name='Année de sortie')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='gestion_academique.departement', verbose_name='Département')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='gestion_academique.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Étudiant archivé',
                'verbose_name_plural': 'Étudiants archivés',
                'ordering': ['-date_archivage'],
                'unique_together': {('etudiant', 'annee_sortie')},
            },
        ),
    ]
