# Generated by Django 5.2.10 on 2026-03-23 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0002_anneeacademique_date_passage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='passage_manuel',
            field=models.BooleanField(default=False, help_text='Cocher si cet étudiant a été passé manuellement par la direction (ignore la règle des 4 dettes)', verbose_name='Passage manuel'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='passage_manuel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du passage manuel'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='passage_manuel_justification',
            field=models.TextField(blank=True, help_text='Raison pour laquelle la direction a forcé le passage', verbose_name='Justification du passage manuel'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='passage_manuel_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_manuels_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Passage effectué par'),
        ),
    ]
