# Generated by Django 5.2.10 on 2026-02-08 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semestres', to='gestion_academique.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['niveau__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('coefficient', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Coefficient')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Crédits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departements', models.ManyToManyField(related_name='matieres', to='gestion_academique.departement', verbose_name='Départements')),
                ('enseignants', models.ManyToManyField(related_name='matieres', to='gestion_academique.enseignant', verbose_name='Enseignants')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='gestion_academique.niveau', verbose_name='Niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='structure_pedagogique.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['niveau__ordre', 'semestre__ordre', 'nom'],
                'unique_together': {('code', 'niveau', 'semestre')},
            },
        ),
    ]
