# Generated by Django 5.2.10 on 2026-02-11 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_pedagogique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Crédits'),
        ),
    ]
