# Generated by Django 5.2.10 on 2026-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Direction'), ('chef_departement', 'Chef de Département'), ('enseignant', 'Enseignant'), ('etudiant', 'Étudiant')], default='etudiant', max_length=30),
        ),
    ]
