# Generated by Django 5.2.10 on 2026-02-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_role'),
    ]

    operations = [
    ]
